version: "2"
services:
  create:
    build: create-file
    image: woa7/wait-for-file:create-file
    volumes:
      - /wait

  wait:
    build: wait-for-file
    image: woa7/wait-for-file
    volumes_from:
      - create
    entrypoint: /wait-for-file.sh /wait/done /bin/sh
