#!/bin/bash

#WORKGING with 19.03.8 
( mkdir $HOME/.docker/ ; true ) && echo $'{\n    "experimental": "enabled"\n}' | tee -a $HOME/.docker/config.json
#WORKGING with 19.03.8 

docker buildx inspect --bootstrap

###!/bin/bash
# thanks https://github.com/se1exin/
# Register qemu-*-static for all supported processors except the
# current one, but also remove all registered binfmt_misc before

docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker buildx inspect --bootstrap

curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | bash -s -- -d

env
set
./bin/seihon publish -v $DOCKER_TAG --image-name $IMAGE_NAME --base-runtime-image alpine --dry-run --targets amd64,arm.v6,arm.v7,arm.v8,arm.v5,386

./bin/seihon publish -v $DOCKER_TAG --image-name $IMAGE_NAME --base-runtime-image alpine --dry-run=false --targets amd64,arm.v6,arm.v7,arm.v8,arm.v5,386
#./bin/seihon publish -v "latest" --image-name $IMAGE_NAME --base-runtime-image alpine --dry-run=false --targets amd64,arm.v6,arm.v7,arm.v8,arm.v5,386
