#!/bin/bash

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

#[ "${BUILD_ARCH}" == "Dockerfile" ] && \
#    { echo 'qemu-user-static: Download not required for current arch'; exit 0; }

# start Enable docker daemon experimental support (for 'docker pull --platform').
  #local -r config='/etc/docker/daemon.json'
  dconfig='/etc/docker/daemon.json'
  if [[ -e "$dconfig" ]]; then
    sudo sed -i -e 's/{/{ "experimental": true, /' "$dconfig" || sed -i -e 's/{/{ "experimental": true, /' "$dconfig"
  else
    echo '{ "experimental": true }' | sudo tee "$dconfig" || echo '{ "experimental": true }' | tee "$dconfig"
  fi
  sudo systemctl restart docker || systemctl restart docker

  # Install QEMU multi-architecture support for docker buildx.
  #docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  docker run --rm --privileged multiarch/qemu-user-static --reset
  #docker run --rm --privileged multiarch/qemu-user-static
  

  # Enable docker CLI experimental support (for 'docker buildx').
  export DOCKER_CLI_EXPERIMENTAL=enabled
  # Instantiate docker buildx builder with multi-architecture support.
  docker buildx create --name mybuilder
  docker buildx use mybuilder
  # Start up buildx and verify that all is OK.
  docker buildx inspect --bootstrap
# end Enable docker daemon experimental support (for 'docker pull --platform').


QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
    | grep 'name.*v[0-9]' \
    | head -n 1 \
    | cut -d '"' -f 4)

###curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
###    | tar xzv
