#!/bin/bash

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

#[ "${BUILD_ARCH}" == "Dockerfile" ] && \
#    { echo 'qemu-user-static: Registration not required for current arch'; exit 0; }

# Register qemu-*-static for all supported processors except the current one
###docker run --rm --privileged multiarch/qemu-user-static:register

# Same as above, but remove all registered binfmt_misc before
#+# docker run --rm --privileged multiarch/qemu-user-static:register --reset

# docker run --rm --privileged multiarch/qemu-user-static:register --reset
# docker run --rm --privileged multiarch/qemu-user-static:register --reset -p yes